# Generated by Django 3.2.7 on 2021-10-10 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DmallComment',
            fields=[
                ('dmallfavorite_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.dmallfavorite')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('imgs', models.ImageField(blank=True, max_length=300, null=True, upload_to='comment/', verbose_name='评论图')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='是否匿名评价')),
                ('rate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.dmallrate', verbose_name='评分')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'db_table': 'd_comment',
            },
            bases=('users.dmallfavorite',),
        ),
    ]
