# Generated by Django 3.2.7 on 2021-10-10 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_del', models.BooleanField(default=False, help_text='删除标记', verbose_name='是否删除')),
                ('is_show', models.BooleanField(default=True, help_text='是否显示', verbose_name='是否显示')),
                ('name', models.CharField(help_text='品牌名', max_length=30, verbose_name='品牌名')),
                ('desc', models.TextField(blank=True, default='', help_text='品牌描述', max_length=200, verbose_name='品牌描述')),
                ('image', models.ImageField(blank=True, help_text='品牌logo', max_length=200, null=True, upload_to='brands/', verbose_name='品牌logo')),
                ('sort', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '品牌',
                'verbose_name_plural': '品牌',
                'db_table': 'd_product_brand',
                'ordering': ['-sort'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_del', models.BooleanField(default=False, help_text='删除标记', verbose_name='是否删除')),
                ('is_show', models.BooleanField(default=True, help_text='是否显示', verbose_name='是否显示')),
                ('name', models.CharField(help_text='分类名称', max_length=30, unique=True, verbose_name='分类名称')),
                ('icon', models.ImageField(blank=True, help_text='大小为48 x 48', max_length=200, null=True, upload_to='product/icon/', verbose_name='分类图标')),
                ('pc_img', models.ImageField(blank=True, help_text='大小为468 x 340', max_length=200, null=True, upload_to='product/pc/icon/', verbose_name='PC分类图')),
                ('is_nav', models.BooleanField(default=False, help_text='是否在导航栏显示', verbose_name='是否导航')),
                ('sort', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('owner', models.ForeignKey(help_text='用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('parent', models.ForeignKey(blank=True, help_text='父级分类，允许为空', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_cate', to='product.productcategory', verbose_name='父级分类')),
            ],
            options={
                'verbose_name': '商品分类',
                'verbose_name_plural': '商品分类',
                'db_table': 'd_product_category',
                'ordering': ['-sort'],
            },
        ),
        migrations.CreateModel(
            name='ProductSKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_del', models.BooleanField(default=False, help_text='删除标记', verbose_name='是否删除')),
                ('is_show', models.BooleanField(default=True, help_text='是否显示', verbose_name='是否显示')),
                ('image', models.ImageField(max_length=200, upload_to='product/sku/', verbose_name='商品主图')),
                ('bar_code', models.CharField(blank=True, default='', max_length=15, verbose_name='商品条码')),
                ('shop_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='售价')),
                ('market_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='市场价')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='成本价')),
                ('product_unit', models.CharField(blank=True, default='', max_length=30, verbose_name='商品单位')),
                ('sales', models.PositiveIntegerField(default=0, verbose_name='销量')),
                ('stock', models.PositiveIntegerField(default=0, help_text='库存', verbose_name='库存')),
                ('owner', models.ForeignKey(help_text='用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'SKU',
                'verbose_name_plural': 'SKU',
                'db_table': 'd_product_sku',
            },
        ),
        migrations.CreateModel(
            name='ProductSPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_del', models.BooleanField(default=False, help_text='删除标记', verbose_name='是否删除')),
                ('is_show', models.BooleanField(default=True, help_text='是否显示', verbose_name='是否显示')),
                ('title', models.CharField(max_length=60, verbose_name='标题')),
                ('sub_title', models.CharField(blank=True, default='', max_length=60, verbose_name='副标题')),
                ('desc', models.CharField(blank=True, default='', max_length=256, verbose_name='简介')),
                ('spec_type', models.PositiveIntegerField(choices=[(0, '单规格'), (1, '多规格')], default=0, verbose_name='规格类型')),
                ('image', models.ImageField(blank=True, max_length=200, null=True, upload_to='product/spu/', verbose_name='商品主图')),
                ('bar_code', models.CharField(blank=True, default='', max_length=15, verbose_name='商品条码')),
                ('shop_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='售价')),
                ('market_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='市场价')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='成本价')),
                ('sales', models.PositiveIntegerField(default=0, verbose_name='销量')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='库存')),
                ('product_unit', models.CharField(blank=True, default='', max_length=30, verbose_name='商品单位')),
                ('content', models.TextField(help_text='详情', verbose_name='商品详情')),
                ('is_new', models.BooleanField(default=False, verbose_name='新品')),
                ('is_hot', models.BooleanField(default=False, verbose_name='热销')),
                ('is_benefit', models.BooleanField(default=False, verbose_name='促销')),
                ('is_best', models.BooleanField(default=False, verbose_name='精品')),
                ('is_release', models.BooleanField(default=True, verbose_name='是否上架')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='brands', to='product.productbrand', verbose_name='品牌')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cat_spu', to='product.productcategory', verbose_name='一级类目')),
                ('category1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cat1_spu', to='product.productcategory', verbose_name='二级类目')),
                ('owner', models.ForeignKey(help_text='用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'db_table': 'd_product_spu',
            },
        ),
        migrations.CreateModel(
            name='ProductSPUSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_del', models.BooleanField(default=False, help_text='删除标记', verbose_name='是否删除')),
                ('is_show', models.BooleanField(default=True, help_text='是否显示', verbose_name='是否显示')),
                ('name', models.CharField(max_length=50, verbose_name='规格名称')),
                ('owner', models.ForeignKey(help_text='用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('spu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spu_spec', to='product.productspu', verbose_name='SPU')),
            ],
            options={
                'verbose_name': '规格',
                'verbose_name_plural': '规格',
                'db_table': 'd_product_spu_spec',
            },
        ),
        migrations.CreateModel(
            name='ProductSPUImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_del', models.BooleanField(default=False, help_text='删除标记', verbose_name='是否删除')),
                ('is_show', models.BooleanField(default=True, help_text='是否显示', verbose_name='是否显示')),
                ('image', models.ImageField(max_length=200, upload_to='product/spu/imgs/', verbose_name='商品图片')),
                ('sort', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
                ('owner', models.ForeignKey(help_text='用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('spu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.productspu', verbose_name='SPU')),
            ],
            options={
                'verbose_name': 'SPU图片',
                'verbose_name_plural': 'SPU图片',
                'db_table': 'd_product_spu_img',
            },
        ),
        migrations.CreateModel(
            name='ProductSpecOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_del', models.BooleanField(default=False, help_text='删除标记', verbose_name='是否删除')),
                ('is_show', models.BooleanField(default=True, help_text='是否显示', verbose_name='是否显示')),
                ('value', models.CharField(max_length=50, verbose_name='选项值')),
                ('owner', models.ForeignKey(help_text='用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='product.productspuspec', verbose_name='规格')),
            ],
            options={
                'verbose_name': '规格选项',
                'verbose_name_plural': '规格选项',
                'db_table': 'd_product_spec_option',
            },
        ),
        migrations.CreateModel(
            name='ProductSKUSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_del', models.BooleanField(default=False, help_text='删除标记', verbose_name='是否删除')),
                ('is_show', models.BooleanField(default=True, help_text='是否显示', verbose_name='是否显示')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.productspecoption', verbose_name='规格值')),
                ('owner', models.ForeignKey(help_text='用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='product.productsku', verbose_name='SKU')),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.productspuspec', verbose_name='规格名称')),
            ],
            options={
                'verbose_name': 'SKU规格',
                'verbose_name_plural': 'SKU规格',
                'db_table': 'd_product_sku_spec',
            },
        ),
        migrations.AddField(
            model_name='productsku',
            name='spu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skus', to='product.productspu', verbose_name='商品'),
        ),
        migrations.AddField(
            model_name='productbrand',
            name='category',
            field=models.ForeignKey(help_text='所属分类', on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='product.productcategory', verbose_name='所属分类'),
        ),
        migrations.AddField(
            model_name='productbrand',
            name='owner',
            field=models.ForeignKey(help_text='用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
