# Generated by Django 3.2.7 on 2021-10-14 00:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='desc',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='分类说明'),
        ),
        migrations.CreateModel(
            name='CategoryAD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_del', models.BooleanField(default=False, help_text='删除标记', verbose_name='是否删除')),
                ('is_show', models.BooleanField(default=True, help_text='是否显示', verbose_name='是否显示')),
                ('image', models.ImageField(blank=True, help_text='大小为468 x 340', max_length=200, null=True, upload_to='product/pc/ad/', verbose_name='PC端楼层广告')),
                ('desc', models.CharField(help_text='广告位所在的位置说明', max_length=100, verbose_name='位置说明')),
                ('url', models.URLField(verbose_name='链接')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productcategory', verbose_name='分类')),
                ('owner', models.ForeignKey(help_text='用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'PC端楼层分类广告',
                'verbose_name_plural': 'PC端楼层分类广告',
                'db_table': 'd_category_ad',
            },
        ),
    ]
