# Generated by Django 3.2.7 on 2021-10-14 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20211014_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryad',
            name='desc',
            field=models.CharField(help_text='广告位所在的位置说明,第一个显示在楼层中间！', max_length=100, verbose_name='位置说明'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='desc',
            field=models.CharField(blank=True, default='', help_text='顶级分类请务必填写，字数限制在8个字，否则PC端楼层显示会有问题！', max_length=100, verbose_name='分类说明'),
        ),
    ]
