# Generated by Django 3.2.7 on 2021-10-10 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_del', models.BooleanField(default=False, help_text='删除标记', verbose_name='是否删除')),
                ('is_show', models.BooleanField(default=True, help_text='是否显示', verbose_name='是否显示')),
                ('img', models.ImageField(blank=True, max_length=200, null=True, upload_to='banners/', verbose_name='轮播图')),
                ('url', models.CharField(help_text="轮播图跳转地址，请以'http://'  或 'https://' 开头", max_length=100, verbose_name='跳转链接')),
                ('desc', models.CharField(blank=True, default='', max_length=100, verbose_name='banner说明')),
                ('sort', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('owner', models.ForeignKey(help_text='用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
                'db_table': 'd_banner',
                'ordering': ['-sort'],
            },
        ),
        migrations.CreateModel(
            name='ADSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_del', models.BooleanField(default=False, help_text='删除标记', verbose_name='是否删除')),
                ('is_show', models.BooleanField(default=True, help_text='是否显示', verbose_name='是否显示')),
                ('name', models.CharField(max_length=50, verbose_name='广告位名称')),
                ('desc', models.CharField(blank=True, default='', max_length=100, verbose_name='广告位置说明')),
                ('owner', models.ForeignKey(help_text='用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '广告',
                'verbose_name_plural': '广告',
                'db_table': 'd_ad_space',
            },
        ),
        migrations.CreateModel(
            name='ADContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_del', models.BooleanField(default=False, help_text='删除标记', verbose_name='是否删除')),
                ('is_show', models.BooleanField(default=True, help_text='是否显示', verbose_name='是否显示')),
                ('ad_choices', models.CharField(choices=[('TXT', '文字广告'), ('IMG', '图片广告'), ('HTML', '富文本广告')], default='IMG', max_length=5, verbose_name='广告类型')),
                ('text', models.CharField(blank=True, default='', max_length=100, verbose_name='文字广告')),
                ('image', models.ImageField(blank=True, max_length=200, null=True, upload_to='ad/', verbose_name='图片广告')),
                ('content', models.TextField(blank=True, default='', verbose_name='富文本广告')),
                ('url', models.URLField(blank=True, default='', help_text='广告类型为文字或图片时的链接跳转地址', verbose_name='广告链接')),
                ('sort', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('ad_space', models.ForeignKey(blank=True, help_text='广告归属于某个广告位', null=True, on_delete=django.db.models.deletion.CASCADE, to='dadmin.adspace', verbose_name='广告位')),
                ('owner', models.ForeignKey(help_text='用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '广告内容',
                'verbose_name_plural': '广告内容',
                'db_table': 'd_ad_content',
                'ordering': ['-sort'],
            },
        ),
    ]
