# Generated by Django 3.2.7 on 2021-10-10 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        ('product', '0001_initial'),
        ('comment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmallorderproduct',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comment.dmallcomment', verbose_name='评价信息'),
        ),
        migrations.AddField(
            model_name='dmallorderproduct',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.dmallorderinfo', verbose_name='订单'),
        ),
        migrations.AddField(
            model_name='dmallorderproduct',
            name='owner',
            field=models.ForeignKey(help_text='用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='dmallorderproduct',
            name='rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.dmallrate', verbose_name='满意度评分'),
        ),
        migrations.AddField(
            model_name='dmallorderproduct',
            name='sku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.productsku', verbose_name='订单规格'),
        ),
        migrations.AddField(
            model_name='dmallorderproduct',
            name='spu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.productspu', verbose_name='订单商品'),
        ),
        migrations.AddField(
            model_name='dmallorderinfo',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.dmalladdress', verbose_name='收货地址'),
        ),
        migrations.AddField(
            model_name='dmallorderinfo',
            name='owner',
            field=models.ForeignKey(help_text='用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterUniqueTogether(
            name='dmallshopingcart',
            unique_together={('owner', 'spu', 'sku')},
        ),
    ]
