# Generated by Django 3.2.7 on 2021-10-10 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_del', models.BooleanField(default=False, help_text='删除标记', verbose_name='是否删除')),
                ('is_show', models.BooleanField(default=True, help_text='是否显示', verbose_name='是否显示')),
                ('name', models.CharField(help_text='分类名称', max_length=30, unique=True, verbose_name='分类名称')),
                ('icon', models.ImageField(blank=True, help_text='大小为48 x 48', max_length=200, null=True, upload_to='cate/icon/', verbose_name='分类图标')),
                ('sort', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('owner', models.ForeignKey(help_text='用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('parent', models.ForeignKey(blank=True, help_text='父级分类，允许为空', null=True, on_delete=django.db.models.deletion.CASCADE, to='article.categorymodel', verbose_name='父级分类')),
            ],
            options={
                'verbose_name': '文章分类',
                'verbose_name_plural': '文章分类',
                'db_table': 'd_category',
                'ordering': ['-sort'],
            },
        ),
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_del', models.BooleanField(default=False, help_text='删除标记', verbose_name='是否删除')),
                ('is_show', models.BooleanField(default=True, help_text='是否显示', verbose_name='是否显示')),
                ('title', models.CharField(help_text='文章标题', max_length=60, verbose_name='标题')),
                ('desc', models.CharField(blank=True, default='', help_text='若为空将默认截取正文开头120个字符，请叫我贴心大哥哥！', max_length=120, verbose_name='文章描述')),
                ('cover', models.ImageField(blank=True, max_length=200, null=True, upload_to='article/cover/', verbose_name='图文封面')),
                ('content', models.TextField(help_text='文章图文详情', verbose_name='文章内容')),
                ('is_banner', models.BooleanField(default=False, help_text='是否Banner', verbose_name='是否Banner')),
                ('is_hot', models.BooleanField(default=False, help_text='是否热门', verbose_name='是否热门')),
                ('is_top', models.BooleanField(default=False, help_text='是否热门', verbose_name='是否置顶')),
                ('category', models.ForeignKey(help_text='文章所属分类', on_delete=django.db.models.deletion.CASCADE, to='article.categorymodel', verbose_name='文章分类')),
                ('owner', models.ForeignKey(help_text='用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '文章详情',
                'verbose_name_plural': '文章详情',
                'db_table': 'd_article',
                'ordering': ['-add_date'],
            },
        ),
    ]
